<div class="container-fluid">
    <div class="block-header">
        <h2>Pages > Manage Top Menu</h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage & Edit Top Menu</h2> 
                    <!--<a href="<?php echo Wo_LoadAdminLinkSettings('add-new-custom-page'); ?>" class="btn btn-info waves-effect waves-light m-t-20">Create New Custom Page</a>-->
                </div>
                <div class="body">
				<?php
				 /* echo '<pre>';
				print_r(Wo_GetCustomMenus()); die; */
				
				?>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                   <th>ID</th>
					               <th>Menu</th>
					               <th>Section</th>
					               <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
								
				                foreach (Wo_GetCustomMenus() as $wo['page']) {
				                    echo Wo_LoadAdminPage('manage-menu-pages/list');
				                }
				                ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function () {
  $('table').DataTable();
});
function Wo_DeleteMenuPage(id) {
  if (id == '') {
    return false;
  }
  if (!confirm('Are you sure you want to delete this page?')) {
    return false;
  }
  $('#' + id).fadeOut(300, function () {
	  $(this).remove();
	});
  $.get(Wo_Ajax_Requests_File(), {f: 'admin_setting', s:'delete_top_menu', id:id});
}
</script>