<tr class="setting-postlist" id="<?php echo $wo['page']['id'];?>">
   <td><?php echo $wo['page']['id'];?></td>
   <td><?php echo $wo['page']['en_menu_title'];?></td>
   <td><?php echo $wo['page']['section_title'];?></td>
   <td>
      <a class="btn btn-info waves-effect waves-light" href="<?php echo Wo_LoadAdminLinkSettings('edit-menu-page?id=' . $wo['page']['id']); ?>">EDIT</a>
      <!--<button class="btn btn-danger waves-effect waves-light" onclick="Wo_DeleteMenuPage(<?php echo $wo['page']['id'];?>);">DELETE</button>-->
   </td>
</tr>