<?php 

$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? Wo_Secure($_GET['query']) : '';
$filter_type    = '';
$db->pageLimit  = 10;


if (!empty($filter_keyword)) {
  $sql   = "(`post_id` LIKE '%$filter_keyword%' OR `postText` LIKE '%$filter_keyword%')";
  $posts = $db->where($sql)->orderBy('id', 'DESC')->objectbuilder()->paginate(T_categories, $page);
} 

else {
  $sql="`created_by`='2' && status !='2'";
  $posts = $db->where($sql)->objectbuilder()->orderBy('id', 'DESC')->paginate(T_categories, $page);
}

if (($page > $db->totalPages) && !empty($_GET['page-id'])) {
  header("Location: " . Wo_LoadAdminLinkSettings('post-board'));
  exit();
}

?>

<div class="container-fluid">
    <div class="block-header">
        <h2>Manage Post Board</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
      <div class="col-lg-12 col-md-12">
        <div class="card">
          <div class="header">
              <h2>Post Board</h2>
          </div>
          <div class="body">
            <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
            <div class="clearfix"></div>
            <div class="table-responsive1">
              <table class="table table-bordered table-striped table-hover">
                  <thead>
                  <tr>
                   <th>ID</th>
                   <th>User</th>
                   <th>Title of Board </th>
                   <th>About The Board</th>
                   
                   <th>Status</th>
                   <th>Action</th>
                  </tr>
                  </thead>
                  <tbody>

                  <?php 
                    foreach ($posts as $post) {
                      $wo['post_baord'] = $post;
                      if (!empty($post->user_id)) {
                        $wo['post_baord']->publisher = Wo_UserData($post->user_id);
                      }
                                           
                      echo Wo_LoadAdminPage('post-board/list');
                    }
                  ?>
                  </tbody>
              </table>
            </div>
            <div class="wo-admincp-feturepager">
                <div class="pull-left">
                    <span>
                      <?php echo "Showing $page out of " . $db->totalPages; ?>
                    </span>
                </div>
                <div class="pull-right">
                    <nav>
                        <ul class="pagination">
                            <li>
                              <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                  <i class="material-icons">first_page</i>
                              </a>
                            </li>
                            <?php if ($page > 1) {  ?>
                              <li>
                                  <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                      <i class="material-icons">chevron_left</i>
                                  </a>
                              </li>
                            <?php  } ?>

                            <?php 
                              $nums       = 0;
                              $nums_pages = ($page > 4) ? ($page - 4) : $page;

                              for ($i=$nums_pages; $i <= $db->totalPages; $i++) { 
                                if ($nums < 20) {
                            ?>
                              <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($i)); ?>" class="waves-effect">
                                  <?php echo $i ?>   
                                </a>
                              </li>

                            <?php } $nums++; }?>

                            <?php if ($db->totalPages > $page) { ?>
                              <li>
                                  <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                      <i class="material-icons">chevron_right</i>
                                  </a>
                              </li>
                            <?php } ?>
                            <li>
                              <a href="<?php echo Wo_LoadAdminLinkSettings('manage-posts?page-id=' . ($db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                  <i class="material-icons">last_page</i>
                              </a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>

<script>

function Wo_AdminDeletePostBoard(post_id) {
    if (confirm("Are you sure you want to delete this post board?") == false) {
      return false;
    }
    hash_id = $('#hash_id').val();
    $('#PostBoardID_' + post_id).fadeOut(300, function() {
       $(this).remove();
    });
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_post_board', {post_board_id:post_id, hash_id:hash_id},function(data, textStatus, xhr) {
      console.log(data);
    });
}

function Wo_AdminApprovePostBoard(post_id) {
    if (confirm("Are you sure you want to approve this post board?") == false) {
      return false;
    }
    hash_id = $('#hash_id').val();
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=approve_post_board', {post_board_id:post_id, hash_id:hash_id}, function(data, textStatus, xhr) {
      location.reload();
    });
}

</script>