<tr class="setting-postlist" id="PostBoardID_<?php echo $wo['post_baord']->id?>" data-post-id="<?php echo $wo['post_baord']->id?>">
   <td><?php echo $wo['post_baord']->id?></td>
   <td>
      <a href="<?php echo $wo['post_baord']->publisher['url']; ?>" target="_blank">
      <img src="<?php echo $wo['post_baord']->publisher['avatar']?>" class="setting-avatar" alt="<?php echo $wo['post_baord']->publisher['avatar']?> Profile Picture">
      <?php echo $wo['post_baord']->publisher['name']; ?>
      </a>
   </td>
   <td><?php echo $wo['post_baord']->name; ?></td>
   <td><?php echo $wo['post_baord']->about_board; ?></td>
   
   <td><?php echo ($wo['post_baord']->status == '1') ? '<span class="label label-success">' . $wo['lang']['active'] . '</span>': '<span class="label label-danger">' . $wo['lang']['pending'] . '</span>';?></td>
   <td>
      <button onclick="Wo_AdminDeletePostBoard(<?php echo $wo['post_baord']->id?>);" type="button" class="btn btn-danger waves-effect waves-light">DELETE</button>
      <?php if ($wo['post_baord']->status == '0') { ?>
         <button onclick="Wo_AdminApprovePostBoard(<?php echo $wo['post_baord']->id?>);" type="button" class="btn btn-success waves-effect waves-light">APPROVE</button>
      <?php } ?>
   </td>
</tr>