<?php 
if (empty($_GET['id'])) {
	die;
   header("Location: " . $wo['config']['site_url']);
   exit();
}
$page = Wo_GetCustomMenu($_GET['id']);
if (empty($page)) {
   header("Location: " . $wo['config']['site_url']);
   exit();
}
?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Pages > Edit Menu</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-8 col-md-8">
            <div class="card">
                <div class="header">
                    <h2>Edit Menu: <?php echo $page['menu_title'] ?></h2>
                </div>
                <div class="body">
                    <div class="alert alert-success add-settings-alert"></div>
                    <form class="add-settings" method="POST">
						<div class="col-lg-6 col-md-6">
							<div class="form-group form-float">
								<div class="form-line">
									<input type="text" id="menu_title" name="menu_title" class="form-control" value="<?php echo $page['menu_title'];?>">
									<label class="form-label">Menu Title in Thai <small> ( The menu title that will show in the top menu )</small></label>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6">
							<div class="form-group form-float">
								<div class="form-line">
									<input type="text" id="en_menu_title" name="en_menu_title" class="form-control" value="<?php echo $page['en_menu_title'];?>">
									<label class="form-label">Menu Title in English <small> ( The menu title that will show in the top menu )</small></label>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6">
							<div class="form-group form-float">
								<div class="form-line">
									<input type="text" id="section_title" name="section_title" class="form-control" value="<?php echo $page['section_title'];?>">
									<label class="form-label">Section Title in Thai <small> ( The title of section )</small></label>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6">		
							<div class="form-group form-float">
								<div class="form-line">
									<input type="text" id="en_section_title" name="en_section_title" class="form-control" value="<?php echo $page['en_section_title'];?>">
									<label class="form-label">Section Title in English <small> ( The title of section )</small></label>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6">	
							<div class="form-group form-float">
								<div class="form-line">
									<textarea name="section_content" id="section_content" class="form-control" cols="30" rows="5"><?php echo br2nl($page['section_content']);?></textarea>
									<label class="form-label">Section Content in Thai <small>The section content (HTML allowed)</small></label>
								</div>
							</div>
						</div>
						<div class="col-lg-6 col-md-6">	
							<div class="form-group form-float">
								<div class="form-line">
									<textarea name="en_section_content" id="en_section_content" class="form-control" cols="30" rows="5"><?php echo br2nl($page['en_section_content']);?></textarea>
									<label class="form-label">Section Content in English <small>The section content (HTML allowed)</small></label>
								</div>
							</div>
						</div>
                        <div class="clearfix"></div>
                        <br>
                        <input type="hidden" value="<?php echo $page['id'];?>" name="menu_id">
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>

$(function() {
    var form_add_settings = $('form.add-settings');
    form_add_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=edit_top_menu',
        beforeSend: function() {
            form_add_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.add-settings-alert').html('<i class="fa fa-check"></i> Menu updated successfully');
                setTimeout(function () {
		            window.location.href = '<?php echo Wo_LoadAdminLinkSettings('manage-menu-pages'); ?>';
		        }, 1000);
            } else if (data.status == 400) {
	          alert(data.message);
	        }
	        form_add_settings.find('.waves-effect').text('Save');
        }
    });
});
</script>