<?php $category_id=$_GET['id']; 

$cat=Wo_GcategoriesById($category_id);
 $categories_keys = Wo_GetPostCategories();
?>

<div class="container-fluid">
	<div class="block-header">
		<h2>Category > Manage Social Post Hub Categories > <!-- <b><?php echo $cat['category']; ?></b> --></h2>
	</div>
	<!-- Vertical Layout -->
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="card">
				<div class="header">
					<h2><b>Manage Categories </b></h2>
				</div>
				<div class="body">
					<div class="clearfix"></div>
					<div class="table-responsive1">
						<table class="table table-bordered table-striped table-hover">
							<thead>
								<tr>
									<th>ID</th>
									<th>Category</th>
									<th>Category in English</th>
									<th>Position</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								foreach ($categories_keys as $categories) 
								{ ?>
									<tr id="list-<?php echo($categories['id']) ?>">
										<td><?php echo $categories['id']; ?></td>
										<td><?php echo $categories['name']; ?></td>
										<td><?php echo $categories['en_name']; ?></td>
										<td><?php echo $categories['position']; ?></td>
										<td>
											<button class="btn bg-cyan waves-effect waves-light"onclick="edit_category('<?php echo($categories['id']) ?>','<?php echo ($categories['name']) ?>','<?php echo ($categories['en_name']) ?>','<?php echo ($categories['position']) ?>')">EDIT</button>
											<?php if ($categories['id'] != 'other') { ?>
											<button class="btn btn-danger waves-effect waves-light delete-content" data-id="<?php echo($categories['id']) ?>">DELETE</button>
											<?php } ?>
										</td>
									</tr>
								<?php   
								} ?>
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>

		<div class="col-lg-12 col-md-12">
			<div class="card">
				<div class="header">
					<h2><b>Add Category</b></h2>
				</div>
				<div class="body">
					<div class="row">
						<div class="col-md-12" style="margin-bottom:0;">
							<div class=" add_category_form_alert"></div>
							<form method="POST" id="add_category_form">
								<div class="row">
									<div class="col-md-2" id="normal-query-form">
										<div class="form-group form-float">
											<div class="form-line">
												<select name="parent_id" class="form-control">
													<option value="0">Select Parent category</option>
													<?php foreach ($categories_keys as $category) {
														echo '<option value="'.$category['id'].'">'.$category['name'].' ('.$category['en_name'].')</option>';
														}
														?>
												</select>
											</div>
										</div>
									</div>
									<div class="col-md-2" id="normal-query-form">
										<div class="form-group form-float">
											<div class="form-line">
												<input type="text" class="form-control" name="category_name">
												<label class="form-label">Category Name in Thai</label>
											</div>
										</div>
									</div>
									<div class="col-md-2" id="normal-query-form">
										<div class="form-group form-float">
											<div class="form-line">
												<input type="text" class="form-control" name="en_category_name">
												<label class="form-label">Category Name in English</label>
											</div>
										</div>
									</div>
									<div class="col-md-2" id="normal-query-form">
										<div class="form-group form-float">
											<div class="form-line">
												<input type="text" class="form-control" name="position">
												<label class="form-label">Position</label>
											</div>
										</div>
									</div>
									<div class="clearfix"></div>
									<div class="col-md-2">
										<button class="btn btn-info">Add</button>
									</div>
								</div>
								<div class="clearfix"></div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		
		<div class="col-lg-12 col-md-12">
			<div class="card">
				<div class="header">
					<h2><b>Manage Sub Categories > <?php echo $cat['category']; ?></b></h2>
				</div>
				<div class="body">
					<div class="clearfix"></div>
					<div class="table-responsive1">
						<table class="table table-bordered table-striped table-hover">
							<thead>
								<tr>
									<th>ID</th>
									<th>Category</th>
									<th>Category in English</th>
									<th>Position</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								foreach ($categories_keys as $categories) 
								{
									if($categories['id'] ==$category_id && !empty($categories['subcat']))
									{
										foreach ($categories['subcat'] as $category) 
										{ 
										
										?>
											<tr id="list-<?php echo($category['id']) ?>">
												<td><?php echo $category['id']; ?></td>
												<td><?php echo $category['name']; ?></td>
												<td><?php echo $category['en_name']; ?></td>
												<td><?php echo $category['position']; ?></td>
												<td>
													<button class="btn bg-cyan waves-effect waves-light" onclick='edit_category("<?php echo($category['id']) ?>","<?php echo ($category['name']) ?>","<?php echo ($category['en_name']) ?>","<?php echo ($category['position']) ?>")'>EDIT</button>
													<?php if ($category['id'] != 'other') { ?>
													<button class="btn btn-danger waves-effect waves-light delete-content" data-id="<?php echo($category['id']) ?>">DELETE</button>
													<?php } ?>
												</td>
											</tr>
										<?php    
										}  
									} 
								} ?>
							</tbody>
						</table>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>

		<div class="clearfix"></div>
	</div>
	<!-- #END# Vertical Layout -->
	
	<div id="delete-modal" class="modal fade" role="dialog" data-id="">
		<div class="modal-dialog">
			<div class="modal-content modal-col-red">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">DELETE Category</h4>
				</div>
				<div class="modal-body">
					<p>Are you sure you want to continue? this action can't be undo</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-link waves-effect" data-dismiss="modal" data-type="user" id="delete_category">DELETE</button>
					<button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade" id="editcategoryModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content modal_content_back">
				<div class="modal-header">
					<h5 class="modal-title" id="editcategoryModalLabel">Edit Category</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					<div class="edit_category_form_alert"></div>
					<form class="edit_category_lang" method="POST" id="modal-body-langs">
						<div class="data_lang"></div>
						<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
						<input type="hidden" name="id_of_key" id="id_of_key" value="">
					</form>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary modal_close_btn" data-dismiss="modal">CLOSE</button>
					<button type="button" class="btn btn-primary" id="save_edited_category">SAVE CHANGES</button>
				</div>
			</div>
		</div>
	</div>

<script>

var add_category_form = $('form#add_category_form');
var edit_category_form = $('form.edit_category_lang');

add_category_form.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=add_social_post_category',
    beforeSend: function() {
        add_category_form.find('.waves-effect').text("Please wait..");
    },
    success: function(data) {
        if (data.status == 200) {
            add_category_form.find('.waves-effect').text('Save');
            $('.add_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Category successfully added</div>');
            setTimeout(function () {
                $('.add_category_form_alert').empty();
            }, 2000);
            window.location.reload();
        }
        else{
          $('.add_category_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
            setTimeout(function () {
                $('.add_category_form_alert').empty();
            }, 2000);
        }
    }
});

edit_category_form.ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_post_hub_category&hash=' + $('.main_session').val(),
    beforeSend: function() {
        edit_category_form.find('.waves-effect').text("Please wait..");
    },
    success: function(data) {
        if (data.status == 200) {
            edit_category_form.find('.waves-effect').text('Save');
            $('.edit_category_form_alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Category successfully edited</div>');
            setTimeout(function () {
                $('.edit_category_form_alert').empty();
            }, 3000);
            window.location.reload();
        }
        else{
          $('.edit_category_form_alert').html('<div class="alert alert-danger"><i class="fa fa-check"></i> '+data.message+'</div>');
            setTimeout(function () {
                $('.edit_category_form_alert').empty();
            }, 2000);
        }
    }
});

$(document).on('click','#save_edited_category', function(event) {
  event.preventDefault();
  $('.edit_category_lang').submit();
});

function edit_category(id,cat_name,en_cat_name,position) {
	$('#id_of_key').val(id);

	var html='<div class="data_lang"><div class="form-group"><div class="form-lins"><label class="form-lasbel">Category Name in Thai</label><input type"text" name="cat_name" id="thai" class="form-control" value="'+cat_name+'" /></div></div><div class="form-group"><div class="form-lins"><label class="form-lasbel">Category Name in English</label><input type"text" name="en_cat_name" id="english" class="form-control" value="'+en_cat_name+'" /></div></div><div class="form-group"><div class="form-lins"><label class="form-lasbel">Position</label><input type"text" name="position" id="english" class="form-control" value="'+position+'" /></div></div></div>';
	
	$('.data_lang').html(html);
	$('#editcategoryModal').modal();
}

$('.delete-content').on('click', function(event) {
    event.preventDefault();
    $('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
  });

$(document).on('click', '#delete_category', function(event) {
    event.preventDefault();
    lang_key = $('#delete-modal').attr('data-id');
    $.post(Wo_Ajax_Requests_File() + '?f=admin_setting&s=delete_post_hub_category', {id: lang_key}, function(data, textStatus, xhr) {
        if (data.status == 200) {
            $('#list-'+lang_key).slideUp('slow');
            setTimeout(function () {
                $('#list-'+lang_key).remove();
            },2000);
        }
    });
});



</script>