<style>
.nav .open > a.cust-lang-menu {
	background-color: transparent;
}
</style>
<div id="welcomeheader" class="navbar-default">
	<div class="container">
		<div class="logo <?php echo Wo_RightToLeft('pull-left');?>">
			<a href="<?php echo $wo['config']['site_url'];?>"><img src="<?php echo $wo['config']['theme_url'];?>/img/logo.<?php echo $wo['config']['logo_extension'];?>" alt="Logo"> </a>
		</div>
		<ul class="nav navbar-nav">
			<li class="dropdown head_name_links">
				<a href="#" class="dropdown-toggle sixteen-font-size btn-help" data-toggle="dropdown" role="button" aria-expanded="false">
					<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
					<path d="M11 11V7h2v4h4v2h-4v4h-2v-4H7v-2h4zm1 11C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm0-2a8 8 0 1 0 0-16 8 8 0 0 0 0 16z" fill="currentColor"/>
					</svg> -->
					<i class="fa fa-question-circle" aria-hidden="true" style="font-size: 25px;"></i>
					<!-- <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" class="hide_fill_svg">
					<path d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10-4.477 10-10 10zm-1-11H7v2h4v4h2v-4h4v-2h-4V7h-2v4z" fill="currentColor"/>
					</svg> -->
				</a>
				<ul class="dropdown-menu clearfix create_head_menu toleft" role="menu">
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/about'); ?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#9c27b0" d="M12,8H4A2,2 0 0,0 2,10V14A2,2 0 0,0 4,16H5V20A1,1 0 0,0 6,21H8A1,1 0 0,0 9,20V16H12L17,20V4L12,8M21.5,12C21.5,13.71 20.54,15.26 19,16V8C20.53,8.75 21.5,10.3 21.5,12Z" /></svg><?php echo ($_GET['lang'] == "english") ? "About" : "เกี่ยวกับ"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/help_center');?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#009da0" d="M18,20H6V18H4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V18H18V20M14,2H6A2,2 0 0,0 4,4V12H6V4H14V8H18V12H20V8L14,2M11,16H8V14H11V16M16,16H13V14H16V16M3,14H6V16H3V14M21,16H18V14H21V16Z" /></svg><?php echo ($_GET['lang'] == "english") ? "Help Centre" : "ศูนย์ช่วยเหลือ"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/account_management');?>"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f25e4e" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" /></svg><?php echo ($_GET['lang'] == "english") ? "Account Management" : "การจัดการบัญชี"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/create_post_board');?>" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#03A9F4" d="M12,6A3,3 0 0,0 9,9A3,3 0 0,0 12,12A3,3 0 0,0 15,9A3,3 0 0,0 12,6M6,8.17A2.5,2.5 0 0,0 3.5,10.67A2.5,2.5 0 0,0 6,13.17C6.88,13.17 7.65,12.71 8.09,12.03C7.42,11.18 7,10.15 7,9C7,8.8 7,8.6 7.04,8.4C6.72,8.25 6.37,8.17 6,8.17M18,8.17C17.63,8.17 17.28,8.25 16.96,8.4C17,8.6 17,8.8 17,9C17,10.15 16.58,11.18 15.91,12.03C16.35,12.71 17.12,13.17 18,13.17A2.5,2.5 0 0,0 20.5,10.67A2.5,2.5 0 0,0 18,8.17M12,14C10,14 6,15 6,17V19H18V17C18,15 14,14 12,14M4.67,14.97C3,15.26 1,16.04 1,17.33V19H4V17C4,16.22 4.29,15.53 4.67,14.97M19.33,14.97C19.71,15.53 20,16.22 20,17V19H23V17.33C23,16.04 21,15.26 19.33,14.97Z" /></svg><?php echo ($_GET['lang'] == "english") ? "Create a Post Board" : "สร้างกระดานโพสต์"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/general_setting'); ?>" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f79f58" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo ($_GET['lang'] == "english") ? "General Settings" : "การตั้งค่าทั่วไป"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/terms_Conditions'); ?>" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f79f58" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo ($_GET['lang'] == "english") ? "Terms and Conditions" : "ข้อกำหนดและเงื่อนไข"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/advertise_with_us'); ?>" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f79f58" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo ($_GET['lang'] == "english") ? "Advertise With Us" : "ลงโฆษณากับเรา"; ?></a>
					</li>
					<li>
						<a href="<?php echo Wo_SeoLink('https://zothai.com/site-pages/privacy_policy'); ?>" ><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="#f79f58" d="M14.4,6L14,4H5V21H7V14H12.6L13,16H20V6H14.4Z" /></svg> <?php echo ($_GET['lang'] == "english") ? "Privacy Policy" : "นโยบายความเป็นส่วนตัว"; ?></a>
					</li> 
				</ul>
			</li>
			
		</ul>
		
		<ul class="nav navbar-nav navbar-right <?php echo Wo_RightToLeft('pull-right');?>" style="padding-right: 55px;">
			<li class="absul-right" style="margin-top: 10px;margin-right: 20px;">
				<span class="lang_selct dropup">
					<a href="#" class="dropdown-toggle cust-lang-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="color: #fff; ">
						<svg height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"><path fill="currentColor" d="M17.9,17.39C17.64,16.59 16.89,16 16,16H15V13A1,1 0 0,0 14,12H8V10H10A1,1 0 0,0 11,9V7H13A2,2 0 0,0 15,5V4.59C17.93,5.77 20,8.64 20,12C20,14.08 19.2,15.97 17.9,17.39M11,19.93C7.05,19.44 4,16.08 4,12C4,11.38 4.08,10.78 4.21,10.21L9,15V16A2,2 0 0,0 11,18M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg> <?php echo $wo['lang']['language'];?>
					</a>
					<ul class="dropdown-menu dropdown-menu-right wow_lang_select_menu">
						<?php
						$langs = Wo_LangsNamesFromDB();
						if (count($langs) > 0) {
							foreach ($langs as $key => $wo['langs']) {
								if ($wo['config'][$wo['langs']] == 1) {
								$language = $wo['langs'];
								$languages_name = ucfirst($wo['langs']);
								$link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;
								
								if($_GET['location'] != '' && $_GET['category'] != "") {
									$link .= '&location='.$_GET['location'].'&category='.$_GET['category'];
								}
						?>
							<li class="language_select"><a href="<?php echo $link;?>" rel="nofollow" class="<?php echo $languages_name;?>"><?php echo $languages_name;?></a></li>
						<?php } } } ?>
					</ul>
				</span>
			</li>	
			<?php if ($wo['config']['user_registration'] == 1): ?>
				<li class="absul-right">
					<a class="mdbtn" href="<?php echo Wo_SeoLink('index.php?link1=login');?>"><?php echo $wo['lang']['login']?></a>
				</li>
				<li class="absul-right">
					<a class="mdbtn" href="<?php echo Wo_SeoLink('index.php?link1=register');?>"><?php echo $wo['lang']['register']?></a>
				</li>
			<?php endif ?>
		</ul>
	</div>
</div>