<meta property="og:title" content="<?php echo $wo['title'];?>" />
      <meta property="og:type" content="article" />
      <meta property="og:image" content="<?php echo Wo_GetMedia($wo['story']['postFile'])?>" />
      <meta property="og:description" content="<?php echo $wo['description'];?>" /> 
      <meta property="og:url" content="<?php echo $wo['config']['site_url'];?>" />
			<meta property="fb:app_id" content="197496131144997"/>   
      <meta name="twitter:title" content="<?php echo $wo['title'];?>" />
      <meta name="twitter:description" content="<?php echo $wo['description'];?>" />
      <meta name="twitter:image" content="<?php echo Wo_GetMedia($wo['story']['postFile'])?>" />
