<meta property="og:type" content="article" />
	  <meta property="og:title" content="<?php echo $wo['story']['postLinkTitle'];?>" />
	  <meta property="og:image" content="<?php echo ($wo['story']['postLinkImage'])?>" />
	  <meta property="og:description" content=" <?php echo ($wo['story']['postLinkContent'])?>" />
	  <meta property="og:url" content="<?php echo $wo['config']['site_url'];?>" />
		<meta property="fb:app_id" content="197496131144997"/>
	  <meta name="twitter:card" content="summary">
      <meta name="twitter:title" content="<?php echo $wo['story']['postLinkTitle'];?>" />
      <meta name="twitter:image" content="<?php echo ($wo['story']['postLinkImage'])?>" />
	  <meta name="twitter:description" content="<?php echo ($wo['story']['postLinkContent'])?>" /> 