<?php
$IsOwner       = Wo_IsOnwer($wo['user_profile']['user_id']);
$IsOwnerUser   = Wo_IsOnwerUser($wo['user_profile']['user_id']);

if ($wo['loggedin'] && $IsOwnerUser) {
   $wo['pr_complition'] = Wo_ProfileCompletion();
}
//echo $_GET['u']."----";
//echo $_GET['type'];die;
//echo "<pre>";print_r($wo);die;
?>
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/tinymce/js/tinymce/tinymce.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script> -->
<!-- <script src="<?php echo $wo['config']['theme_url'];?>/assets/js/bootstrap4.masonry.js"></script>
<script>
$(function() {
    var $masonry = $('.masonry').masonry();
});
</script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.1/masonry.pkgd.min.js"></script>
<script>
  //init masonry grid 
$(window).on("load", function() {
	$('.masonry').masonry({
    itemSelector: '.post-container',
    percentPosition: true,
    horizontalOrder: true,

  });
});

</script>
<div class="row page-margin profile wo_user_profile" data-page="timeline" data-id="<?php echo $wo['user_profile']['user_id'];?>">
	<div class="profile-container">
		<?php echo Wo_LoadPage('timeline/top-bar');?>
	</div>
	<?php 
	$IsUserFriend  = Wo_IsUserFriend($wo['user_profile']['user_id']);
	 $logged_user_id = Wo_Secure($wo['user']['user_id']);

	//echo '------------='.$wo['user_profile']['user_id'].'-------'.$wo['user']['user_id'].var_dump($IsUserFriend); die; 
	//if(($wo['user_profile']['user_id'] == $logged_user_id) || ($wo['user_profile']['profile_privacy']=='0') || ($wo['user_profile']['profile_privacy']=='1' && $IsUserFriend==true)) 
	// if(($wo['user_profile']['user_id'] == $logged_user_id) || ($wo['user_profile']['profile_privacy']=='0')) 
	// {
		?>

		<div class="col-md-12" style="margin: 0px 0px 20px 0px;">
			
			<h3 class="post-hub" style="padding-top: 5px;"><?php echo $wo['lang']['profile_page_site'];?></h3>
			<div class="user-bottom-nav">
				<ul>
					<li>
						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '');?>" >
							<span class="split-link">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
									<path  d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z" fill="currentColor"></path>
								</svg>
							</span>
							<span><?php echo $wo['lang']['short_posts'];?></span>
						</a>
					</li>
				
					<li>
						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=blog');?>" >
							<span class="split-link">
								<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
									<path d="M20,11H4V8H20M20,15H13V13H20M20,19H13V17H20M11,19H4V13H11M20.33,4.67L18.67,3L17,4.67L15.33,3L13.67,4.67L12,3L10.33,4.67L8.67,3L7,4.67L5.33,3L3.67,4.67L2,3V19A2,2 0 0,0 4,21H20A2,2 0 0,0 22,19V3L20.33,4.67Z" fill="currentColor"></path>
								</svg>
							</span>
							<span><?php echo $wo['lang']['long_posts'];?></span>
						</a>
					</li>
				
					<li>
						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=events');?>">
							<span class="split-link">
								<!--svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
									<path d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" fill="currentColor"></path>
								</svg-->
								<img src="https://klickpal.com/upload/photos/mini_img.png" style="width: 20%; margin-bottom: 3px;">
							</span>
							<span><?php echo $wo['lang']['mini'];?></span>
						</a>
					</li>
					<?php if($wo['user_profile']['profile_type']=='3'){ ?>
						<li>
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=shop');?>" >
              <span class="split-link"><img src="<?php echo $wo['config']['theme_url'];?>/img/my_showroom.png" style="width: 20%; margin-bottom: 3px;"></span>
							<span><?php echo $wo['lang']['showroom'];?></span>
						</a>

						</li>	
					<?php }elseif($wo['user_profile']['profile_type']=='2'){ ?>
						<li>
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=portfolio');?>" >
              <span class="split-link"><img src="<?php echo $wo['config']['theme_url'];?>/img/my_show.png" style="width: 20%; margin-bottom: 3px;"></span>
							<span><?php echo $wo['lang']['my_show'];?></span>
						</a>

						</li>	
					<?php } else{ ?>
						<li>
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=photos');?>" >
              <span class="split-link"><img src="<?php echo $wo['config']['theme_url'];?>/img/mylikes.png" style="width: 20%; margin-bottom: 3px;"></span>
							<span><?php echo $wo['lang']['my_likes'];?></span>
						</a>

						</li>	
					<?php } if(($wo['user_profile']['user_id'] == $logged_user_id) || ($wo['user_profile']['for_yous_privacy']=='0')) { ?>
						<li>
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=feed');?>" >
								<span class="split-link">
									<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24">
										<path d="M11 4h10v2H11V4zm0 4h6v2h-6V8zm0 6h10v2H11v-2zm0 4h6v2h-6v-2zM3 4h6v6H3V4zm2 2v2h2V6H5zm-2 8h6v6H3v-6zm2 2v2h2v-2H5z" fill="currentColor"></path>
									
									</svg>
								</span>
								<span><?php echo $wo['lang']['for_me'];?></span>
							</a>
						</li>
						<?php } if(($wo['user_profile']['user_id'] == $logged_user_id) || ($wo['user_profile']['post_page_privacy']=='0')) {?>
						<li> 
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=myposts');?>" >
								<span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M5 3A2 2 0 0 0 3 5H5M7 3V5H9V3M11 3V5H13V3M15 3V5H17V3M19 3V5H21A2 2 0 0 0 19 3M3 7V9H5V7M7 7V11H11V7M13 7V11H17V7M19 7V9H21V7M3 11V13H5V11M19 11V13H21V11M7 13V17H11V13M13 13V17H17V13M3 15V17H5V15M19 15V17H21V15M3 19A2 2 0 0 0 5 21V19M7 19V21H9V19M11 19V21H13V19M15 19V21H17V19M19 19V21A2 2 0 0 0 21 19Z" fill="currentColor"></path></svg></span>
								<span><?php echo $wo['lang']['my_posts'];?></span>
							</a>
						</li>
					<?php }
					//echo "<pre>";print_r($wo['user_profile']);
					//echo $wo['user_profile']['profile_privacy']."i am there";die;
					if(($wo['user_profile']['user_id'] == $logged_user_id) || ($wo['user_profile']['friend_privacy']=='0')) 
					{  ?>
						<li>
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=friends');?>" >
								<span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" fill="currentColor"></path></svg></span>
								<span><?php echo $wo['lang']['friends'];?> </span>
							</a>
						</li>
					<?php } if(($wo['user_profile']['user_id'] == $logged_user_id) || ($wo['user_profile']['followers_privacy']=='0')) {?>
						<li>
							<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=followers');?>" >
								<span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" fill="currentColor"></path></svg></span>
								<span><?php echo $wo['lang']['followers'];?> </span>
							</a>
						</li>
					<?php } if ($wo['config']['pages'] == 1) {?>
					<li>
						<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=likes');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=likes">
							<span class="split-link"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M23,10C23,8.89 22.1,8 21,8H14.68L15.64,3.43C15.66,3.33 15.67,3.22 15.67,3.11C15.67,2.7 15.5,2.32 15.23,2.05L14.17,1L7.59,7.58C7.22,7.95 7,8.45 7,9V19A2,2 0 0,0 9,21H18C18.83,21 19.54,20.5 19.84,19.78L22.86,12.73C22.95,12.5 23,12.26 23,12V10M1,21H5V9H1V21Z" fill="currentColor"></path></svg></span>
							<span><?php echo $wo['lang']['likes'];?></span>
						</a>
					</li>
					<?php } ?>
					
                
				</ul>
			</div>
		</div>
		</div>
		<?php   
				if (isset($_GET['type'])) 
				{
						if($_GET['type']=='blog')
						{
							echo Wo_LoadPage('timeline/blog-board');
						}
						elseif($_GET['type']=='events')
						{
							echo Wo_LoadPage('timeline/events-board');
						}	
						elseif($_GET['type']=='feed' && ($wo['user_profile']['user_id'] == $logged_user_id))
						{
							echo Wo_LoadPage('timeline/feed-board');
						}	
						elseif($_GET['type']=='photos' && $wo['user_profile']['profile_type']=='1' )
						{
							echo Wo_LoadPage('timeline/photo-board');
						}
						elseif($_GET['type']=='portfolio' && $wo['user_profile']['profile_type']=='2' )
						{
							echo Wo_LoadPage('timeline/portfolio-board');
						}	
						elseif($_GET['type']=='shop' && $wo['user_profile']['profile_type']=='3' )
						{
							echo Wo_LoadPage('timeline/shop-board');
						}		
						elseif($_GET['type']=='myposts' && ($wo['user_profile']['user_id'] == $logged_user_id))
						{
							echo Wo_LoadPage('timeline/my-posts');
						}	
						elseif($_GET['type']=='friends')
						{
							echo Wo_LoadPage('timeline/friends-list');
						}
						elseif($_GET['type']=='followers')
						{
							echo Wo_LoadPage('timeline/follow-list');
						}
						elseif($_GET['type']=='likes')
						{
							echo Wo_LoadPage('timeline/likes');
						}
						else
						{
							echo Wo_LoadPage('timeline/post-board');
						}					 
				}
				else
				{
						echo Wo_LoadPage('timeline/post-board');
				}
	/*} 
	else
	{
		echo Wo_LoadPage('story/profile-no-access');
	}*/



	 ?>

</div>

<?php echo Wo_LoadPage('modals/unfriend');?>
<?php echo Wo_LoadPage('modals/profile-picture');?>
<?php echo Wo_LoadPage('modals/cover-image');?>
<?php /*if (!empty($wo['user_profile']['background_image']) && $wo['user_profile']['background_image_status'] == 1) { ?>
<style>
  body {
    background: url(<?php echo Wo_GetMedia($wo['user_profile']['background_image']); ?>) fixed !important;
    background-size:100% auto;
  }
</style>
<?php }*/ ?>
<!-- JS Timline functions -->
<?php if ($wo['loggedin']): ?>
<div class="modal fade" id="send_gift" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-gift"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg>
                    <?php echo $wo['lang']['send_a_gift']; ?>
				</h4>
			</div>
			<div class="modal-body">
                <div id="gifts-list" class="wo_send_gift">
                    <?php foreach (Wo_GetAllGifts(500000) as $wo['giftlist']) {?>
                        <div class="text-center gift-data" data-gift-id="<?php echo $wo['giftlist']['id'];?>">
                            <label>
                                <input type="radio" onClick="$('#send-gift-button').attr('data-gift-id',$(this).val());$('#send-gift-button').attr('data-gift-img','<?php echo $wo['giftlist']['media_file'];?>');$('#send-gift-button').attr('disabled',false);" name="gift" value="<?php echo $wo['giftlist']['id'];?>" />
                                <img src="<?php echo Wo_GetMedia($wo['giftlist']['media_file']); ?>" alt="<?php echo $wo['giftlist']['name'];?> gift">
                            </label>
                        </div>
                    <?php } ?>
                </div>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn  btn-main" id="send-gift-button" data-gift-id="" data-gift-img="" onclick="Wo_SendGiftToUser(<?php echo $wo['user']['id']; ?>,<?php echo $wo['user_profile']['id']; ?>,this)" disabled><?php echo $wo['lang']['send']; ?></button>
			</div>
		</div>
	</div>
</div>
<?php endif; ?>
<div class="modal fade" id="report_profile" role="dialog">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>
					<?php echo $wo['lang']['report_user']; ?>
				</h4>
			</div>
			<div class="modal-body">
				<textarea class="form-control" placeholder="Type text" dir="auto" rows="4" id="report-user-text-<?php echo $wo['user_profile']['id']; ?>"></textarea>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn  btn-main" id="report-user-button" onclick="Wo_ReportProfile(<?php echo $wo['user_profile']['id']; ?>,true)"><?php echo $wo['lang']['send']; ?></button>
			</div>
		</div>
	</div>
</div>
<?php if ($wo['loggedin']): ?>
	<div class="modal fade" id="add_to_family" role="dialog">
		<div class="modal-dialog wow_mat_mdl">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
					<h4 class="modal-title"><?php echo $wo['lang']['family_member']; ?></h4>
				</div>
				<div class="add_to_family_alert"></div>
				<div class="modal-body">
					<div class="col-md-3">
						<div class="family_mbr_avatar">
							<img src="<?php echo $wo['user_profile']['avatar']; ?>" alt="<?php echo $wo['user_profile']['name']; ?> Picture" class="responsive-img">
						</div>
					</div>
					<div class="col-md-9">
						<h4 class="family_mbr_name"><?php echo $wo['user_profile']['name']; ?></h4>
						<?php if($wo['config']['user_lastseen'] == 1 && $wo['user_profile']['showlastseen'] != 0): ?>
							<div class="user-lastseen">
								<?php echo Wo_UserStatus($wo['user_profile']['user_id'],$wo['user_profile']['lastseen']); ?>
							</div>
						<?php endif; ?>
						<div  class="add_as_cont">
							<div class="col-md">
								<label class="main">
									<small><?php echo $wo['lang']['add_as']; ?>*</small>
								</label>
							</div>
							<div class="col-md-">
								<select class="form-control" name="family_list" id="family_list" title="Add as.">
									<?php foreach ($wo['family'] as $key => $value): ?>
										<option value="<?php echo $key; ?>">
											<?php echo $wo['lang'][$value]; ?>
										</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="clear"></div>
						</div>
					</div>
					<div class="clear"></div>
				</div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="button" class="btn btn-main btn-mat" id="add_to_family_button" onclick="Wo_AddFamilyMember();"><?php echo $wo['lang']['save']; ?></button>
				</div>
			</div>
		</div>
	</div>
<?php endif; ?>
<div class="modal fade" id="delete_family_mbr_modal"  role="dialog" data-slide='true'>
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['important']; ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $wo['lang']['confirm_remove_family_member']; ?></p>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button id="delete_family_member_button"  type="button" class="btn btn-main" onclick="Wo_DeleteFamilyMember($('#delete_family_mbr_modal').attr('data-family-member-id'));"><?php echo $wo['lang']['delete']; ?></button>
			</div>
		</div>
	</div>
</div>
<div class="modal fade in" id="poke_modal" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
				<i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
				<?php echo $wo['lang']['you_have_poked'] . " " . ucfirst($wo['user_profile']['username']); ?>
			</p>
		</div>
	</div>
</div>
<div class="modal fade in" id="accept_family_mbr_modal" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<p style="text-align: center;padding: 30px 20px;font-family: Hind,Arial;font-size: 16px;">
				<i class="fa fa-check" aria-hidden="true" style="color: green;"></i>      
				<?php echo $wo['lang']['family_member_added']; ?>
			</p>
		</div>
	</div>
</div>
<div class="modal fade" id="cropImage" role="dialog">
	<div class="modal-dialog wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['crop_your_avatar'] ?></h4>
			</div>
			<div class="modal-body">
				<div id="image-to-crop" class="wo_crop_img_pic">
					<img src="<?php echo Wo_GetMedia($wo['user_profile']['avatar_full'])?>" alt="avatar" data-image="<?php echo $wo['user_profile']['avatar_full']; ?>" >
				</div>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<button type="button" class="btn btn-main btn-mat" onclick="CropImage();"><?php echo $wo['lang']['save']; ?></button>
			</div>
		</div>
	</div>
</div>
<?php if ( $wo['loggedin'] ): ?>
    <?php if ( isset( $_GET['mode'] ) && $_GET['mode'] == 'opengift' ): ?>
        <div class="modal fade" id="gift_show_model" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
                        <h4 class="modal-title">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-gift"><polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path></svg>
                        <?php echo $wo['user_profile']['name'] . " " . $wo['lang']['send_gift_to_you'] ?></h4>
                    </div>
                    <div class="modal-body">
                        <img src="<?php echo Wo_GetMedia($_GET['gift_img']);?>" style="max-width: 100%;margin: 0 auto;display: block;">
                    </div>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>

<!-- Edit title box -->
<?php if ( $wo['loggedin'] ): ?>
       <div class="modal fade" id="edit_professional_title" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                       <h4 class="modal-title"><?php echo $wo['lang']['change_your_title'];?>
                        </h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
                       
                    </div>
                   <!--  <form method="post" action="#"> -->
                    <div class="modal-body">
                      
                    <label><?php echo $wo['lang']['enter_your_title'];?></label>  
                      <div class="form-group">
                        <input type="text" id="set_title"  class="form-control input-md"  autocomplete="off" placeholder="Caption this image" >
                        <span class="help-block checking"></span>  
                      
                    </div>
                    <label><?php echo $wo['lang']['link'];?></label>  
                      <div class="form-group">
                        <input type="text" id="set_link"  class="form-control input-md"  autocomplete="off">
                        <span class="help-block checking"></span>  
                      
                    </div>
                    </div>

                    <div class="modal-footer">
                        <button type="submit" class="btn btn-main" onclick="save_my_status()" ><?php echo $wo['lang']['save'];?></button>
                    </div>
                   <!--  </form> -->
                </div>
            </div>
        </div>
<?php endif; ?>

<style>
	.post-youtube iframe {
		height: 362px !important;
	}
	.card-footer a {
    color: #fff;
}
</style>
<script>

	function wo_open_title_box($title_id)
{ //alert($title_id);

  var title='title_'+$title_id;
  var link='link_'+$title_id;
  var titleValue = $("#"+title).text();
  var linkValue = $("#"+link).val();
  console.log(titleValue+'--'+title);
  $('#set_title').attr('name', title);
  //$('#set_title').attr('value', titleValue);
 // $('#set_title').val(titleValue);
  $('#set_link').val(linkValue);
   $('#set_link').attr('name', link);
  $('#edit_professional_title').modal('show');
}
function save_my_status()
{
  var new_title=$('#set_title').val();
  var attr_name=$('#set_title').attr('name');
  var userid='<?php echo $wo['user_profile']['user_id']; ?>';
  var new_link=$('#set_link').val();
  var link_name=$('#set_link').attr('name');
  //var pageplacement='personal';
  //var pageid='<?php echo $wo['page_profile']['page_id']; ?>';
  console.log(link_name+'---'+attr_name);
 

  $.post(Wo_Ajax_Requests_File() + '?f=update_user_status', {user_id:userid, title:new_title,name:attr_name,link:new_link}, function(data, textStatus, xhr) {
    console.log(data.status);
    console.log(data);
        if (data.status == 200) 
        {
          $('#edit_professional_title').modal('hide');
          $('#'+attr_name).html(new_title);
          $('#'+link_name).val(new_link);
          $('.'+link_name).attr("href", new_link)
          $('#set_title').val('');
          $('#set_link').val('');
        } 
       
    });


}





$(function(){
    var url = window.location.pathname, 
        urlRegExp = new RegExp(url.replace(/\/$/,'') + "$"); // create regexp to match current url pathname and remove trailing slash if present as it could collide with the link in navigation in case trailing slash wasn't present there
        // now grab every link from the navigation
        $('.user-bottom-nav a').each(function(){
            // and test its normalized href against the url pathname regexp
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                $(this).addClass('menuactive');
            }
        });
});

function Wo_open_send_gift(){
    $('#send_gift').modal('show');
}

function Wo_SendGiftToUser(from, to){
    var gift_id = $('#send-gift-button').attr('data-gift-id');
    var gift_img = $('#send-gift-button').attr('data-gift-img');

    if (!from || !to || !gift_id) {
        return false;
    }

    $('#send-gift-button').attr('disabled','');
	$('#send_gift').find('.ball-pulse').fadeIn(100);
	
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'send_gift',from:from,to:to,gift_id:gift_id,gift_img:gift_img},
    })
    .done(function(data) {
        if (data.status == 200) {
            $('#send-gift-button').html('<?php echo $wo['lang']['gift_sent_succesfully']; ?>');
			$('#send_gift').find('.ball-pulse').fadeOut(100);
            Wo_Delay(function(){
                $("#send_gift").modal('hide');
                $('#send-gift-button').attr('data-gift-id', '').attr('data-gift-img', '').attr('disabled',false).html('<?php echo $wo['lang']['send']; ?>');
            },1500);
        }
    })
    .fail(function() {
        console.log("error");
    })
    
}

function Wo_RegisterPoke(received_user_id , send_user_id){
    if (!received_user_id || !send_user_id) {
        return false;
    }
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'poke',received_user_id:received_user_id,send_user_id:send_user_id},
    })
    .done(function(data) {
        if (data.status == 200) {
            $("#poke_modal").modal('show');
            $("#pokebutton").remove();
            Wo_Delay(function(){
                $("#poke_modal").modal('hide');
            },1500);
        }
    })
    .fail(function() {
        console.log("error");
    })
}

function Wo_ActivateFamilyMember(id = false,self = false,member = false){
    if (!id || !self || !member) {
        return false;
    }
    Wo_progressIconLoader($(self).find('i'));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'accept_member',id:id,type:member},
    })
    .done(function(data) {
        if (data.status == 200) {
            $("#accept_family_mbr_modal").modal('show');
            $('[data-family-member="'+id+'"]').slideUp(function(){
                    $(this).remove();
            })
            Wo_Delay(function(){
                $("#accept_family_mbr_modal").modal('hide');
            },1500);
        }
    })
    .fail(function() {
        console.log("error");
    })
    Wo_progressIconLoader($(self).find('i'));
}

function Wo_AcceptRelationRequest(id = false,member = false,type = false ,self = false){
    if (!member || !self || !type || !id) {
        return false;
    }
    Wo_progressIconLoader($(self));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'accept_relation',id:id,type:type,member:member},
    })
    .done(function(data) {
        if (data.status == 200) {
            window.location = data.url;
        }
    })
    .fail(function() {
        console.log("error");
    })
}

function Wo_DeleteRelationRequest(id = false,user = false,type = false,self = false){
    if (!self || !id || !user || !type) {
        return false;
    }
    Wo_progressIconLoader($(self).find('i'));
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'delete_relation',id:id,user:user,type:type},
    })
    .done(function(data) {
        if (data.status == 200) {
            $("[data-relationship-request='"+id+"']").slideUp(function(){
                $(this).remove();
            })
        }
    })
    .fail(function() {
        console.log("error");
    })
    Wo_progressIconLoader($(self).find('i'));
}

function OpenCropModal() {
	$('#cropImage').modal('show');
	setTimeout(function () {
    	$('#image-to-crop img').rcrop({
            minSize : [130,130],
            preserveAspectRatio : true,
            grid : true,
        });
    }, 250);
}
function CropImage() {
    values = $('#image-to-crop img').rcrop('getValues');
    $path = $('#image-to-crop img').attr('data-image');
    if (!$path) {
    	return false;
    	$('#cropImage').modal('hide');
    }
    $('#cropImage').find('.ball-pulse').fadeIn(100);
    $.post(Wo_Ajax_Requests_File() + '?f=crop-avatar', {user_id:<?php echo $wo['user_profile']['id']; ?>, path: $path, x: values.x, y:values.y, height: values.height, width:values.width}, function(data, textStatus, xhr) {
        if (data.status == 200) {
        	location.reload(false);
        } else {
        	$('#cropImage').modal('hide');
        }
        $('#cropImage').find('.ball-pulse').fadeOut(100);
    });
}
function Wo_DeleteFamilyMember(id = false){
    if (!id) {
        return false;
    }
    $('#delete_family_mbr_modal').find('.modal-footer .ball-pulse').fadeIn(100);
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'delete_member',id:id},
    })
    .done(function(data) {
        if (data.status == 200) {
            $('[data-family-member="'+id+'"]').slideUp('slow',function(){
                    $(this).remove();
            })
            Wo_Delay(function(){
                $("#delete_family_mbr_modal").modal('hide');
            },1500);
        }
        $('#delete_family_mbr_modal').find('.modal-footer .ball-pulse').fadeOut(100);
    })
    .fail(function() {
        console.log("error");
    })
}

function Wo_AddFamilyMember(){
    var member_type = $("#family_list").val();
    if (!member_type || member_type < 1 || member_type > 43) {
        return false;
    }
    $('#add_to_family').find('.modal-footer .ball-pulse').fadeIn(100);
    $('#add_to_family').find('.btn-main').attr('disabled', 'true');
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {
            f: 'family',
            s:'add_member',
            member_id:'<?php echo $wo['user_profile']['user_id']; ?>',
            type:member_type
        },
    })
    .done(function(data) {
        if (data.status == 200) {
            $('.add_to_family_alert').html('<div class="alert alert-success">' + data.message + '</div>');
            Wo_Delay(function(){
                $("#open_add_to_family_modal").slideUp(function(){
                    $(this).remove();
                    $("#add_to_family").modal('hide');
                })
                $('#add_to_family').find('btn-main').removeAttr('disabled');
                location.reload()
            },1500);
            
        }
        else{
            $('.add_to_family_alert').html('<div class="alert alert-success">' + data.message + '</div>');
            $('#add_to_family').find('.btn-main').removeAttr('disabled');
        }
        $('#add_to_family').find('.modal-footer .ball-pulse').fadeOut(100);
    })
    .fail(function() {
        console.log("error");
    })  
}

function Wo_ReportProfile(id = false,report = true){
    var report_text = $("#report-user-text-<?php echo $wo['user_profile']['id']; ?>").val();
    if (!id) {return false;}
    else if(report == true){
      if (!report_text) {return false;}  
    }
    $('#report_profile').find('.modal-footer .ball-pulse').fadeIn(100);
    $.ajax({
        url: Wo_Ajax_Requests_File() + '?f=reports&s=report_user',
        type: 'POST',
        dataType: 'json',
        data: {text:report_text,user:id},
    })
    .done(function(data) {
        if(data.status == 200 && data.code == 0){
            $('#report_status').replaceWith('\
                <li id="report_status" onclick="$(\'#report_profile\').modal(\'show\');">\
                    <span class="menu-item"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>\
                    <span><?php echo $wo['lang']['report_user']; ?></span></span>\
                </li>');
        }

        else if (data.status == 200 && data.code == 1) {
            $("#report-user-text-<?php echo $wo['user_profile']['id']; ?>").val('');
            $("#report_profile").modal('hide');
            $('#report_status').replaceWith('\
                <li id="report_status" onclick="Wo_ReportProfile(<?php echo $wo['user_profile']['id']; ?>,false);">\
                    <span class="menu-item"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-alert-triangle"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12" y2="17"></line></svg>\
                    <span><?php echo $wo['lang']['unreport']; ?></span></span>\
                </li>');
        }
        $('#report_profile').find('.modal-footer .ball-pulse').fadeOut(100);
    })
    .fail(function() {
        console.log("error");
    })
}

function loadposts(user_id) {
  $.get(Wo_Ajax_Requests_File() + '?f=load_profile_posts', {user_id:user_id}, function(data) {
    $('.posts_load').html(data);
  });
}

var user_id = $('.profile').attr('data-id');
$(function () {
  user_id = $('.profile').attr('data-id');
  <?php 
  if (!empty($_GET['story'])) {
    ?>
    Wo_LoadStory('prof', $('[data-page=timeline]').attr('data-id'));
    <?php
  }
  ?>
  if($(window).width() > 600) {
    $(".user-avatar").hover(function () {
      $('.profile-avatar-changer').fadeIn(100);
    }, function () {
      $('.profile-avatar-changer').fadeOut(100);
    });
  }
  if($(window).width() > 600) {
    $(".card-img-holder").hover(function () {
      $(this).find('.profile-cover-changer').fadeIn(100);
    }, function () {
      $(this).find('.profile-cover-changer').fadeOut(100);
    });
  }
  
  $('form.profile-avatar-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_avatar_picture',

    beforeSend: function () {
      $('.profile_avatar').fadeOut(100);
      $('.user-avatar-uploading-container, .user-avatar-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      $('.profile_avatar').fadeIn(100);
      if(data.status == 200) {
        Wo_GetNewPosts();
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr('data-target', '#ProfileImageModal-Stopped'); 
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr('onclick', 'Wo_OpenProfilePicture("' + data.img_or + '");');
        $('[id^=updateImage-<?php echo $wo['user_profile']['id']; ?>]').attr("src", data.img);
        $('#cropImage').modal('show');
        $('#image-to-crop img').attr('src', data.avatar_full);
        $('#image-to-crop img').attr('data-image', data.avatar_full_or);
        $('#image-to-crop img').on("load", function() {
		    setTimeout(function () {
		    	$('#image-to-crop img').rcrop({
		            minSize : [100,100],
		            preserveAspectRatio : true,
		            grid : true
		        });
		    }, 1000);
		}).each(function() {
		  if(this.complete) $(this).load();
		});
        if($("ul[data-profile-completion]").length == 1) {
            if ($('#add-profile-avatar').length == 1) {
               // window.location.reload();
            }
        }
      }

      $('.user-avatar-uploading-container,.user-avatar-uploading-progress').fadeOut(200);
    }
  });

  $('form.cover-position-form').ajaxForm({
        url:  Wo_Ajax_Requests_File() + '?f=re_cover',
        dataType:  'json', 
        beforeSend: function() {
            $('.user-reposition-dragable-container').hide();
            $('.user-repositioning-icons-container1').show();
            $('.user-repositioning-icons-container').html('<div class="pace-activity-parent"><div class="pace-activity"></div></div>').fadeIn('fast');
        },
        success: function(data) {
            if (data.status == 200) {
                $('.user-cover-reposition-w img').attr('src', data.url + '?time=' + Math.random()).on("load", function () {
                    $('.when-edit').hide();
                    $('.when-notedit').show();
                    $('.user-repositioning-icons-container1').fadeOut('fast');
                    $('.user-repositioning-icons-container').fadeOut('fast').html('');
                    $('.user-cover-reposition-w').show();
                    $('.user-reposition-container').hide().find('img').css('top', 0);
                    $('.cover-resize-buttons').hide();
                    $('.default-buttons').show();
                    $('input.cover-position').val(0);
					$('.wo_user_profile .card.hovercard .pic-info-cont, .problackback').fadeIn();
                    // /$('.user-reposition-container img').draggable('destroy').css('cursor','default');
                    
                });
            }
        }
    });
	/* $('.profile-cover-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_user_cover_picture',

    beforeSend: function () {
      $('.profile_cover').fadeOut(100);
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
    },
    success: function (data) {
    	console.log(data);
      $('.profile_cover').fadeIn(100);
      if(data.status == 200) {
        Wo_GetNewPosts();
        var image_id='cover-image-'+data.cover_id
        $('[id^='+image_id+']').attr("src", data.img);
        // $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal-Stopped');      
        // $('[id^=cover-image]').attr('onclick', 'Wo_OpenProfileCover("' + data.cover_or + '");');
        // $('[id^=cover-image]').attr("src", data.img);
        // $('#full-image').attr("src", data.cover_full);
        // $('#full-input-image').val(data.cover_full);
        // $('#cover-input-image').val(data.cover_or);
        // Wo_StartRepositioner();
      }
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
    }
  }); */
  
	$("#coverInpt").change( function (){
		var fileExtension = ['jpeg', 'jpg', 'png', 'mp4', 'mov'];
        if ($.inArray($(this).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only formats are allowed : "+fileExtension.join(', '));
			$(this).val("");
        }
	});
	
	$("#video_thumbnail").change( function (){
		var fileExtension = ['jpeg', 'jpg', 'png'];
        if ($.inArray($(this).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only formats are allowed : "+fileExtension.join(', '));
			$(this).val("");
        }
	});
	
	$('#updateProfileCoverMdl').on('shown.bs.modal', function (e) {
		$(".coverProgress").hide();
		var percentVal = '0%';
		bar.width(percentVal);
		percent.html(percentVal);
		
		$("#updateCoverMsg").html("");
		$('#updateCoverFrm').trigger("reset");
		$("#updateCoverBtn").attr("disabled", false);
	});
	
	var bar = $('#coverbar');
	var percent = $('#coverpercent');
  
	$('#updateCoverFrm').ajaxForm({
		url: Wo_Ajax_Requests_File() + '?f=update_user_cover_picture',
		beforeSend: function () {
			$("#updateCoverBtn").attr("disabled",true);
			$('.profile_cover').fadeOut(100);
			$('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
			var percentVal = '0%';
			bar.width(percentVal);
			percent.html(percentVal);
		},
		uploadProgress: function (event, position, total, percentComplete) {
			var percentVal = percentComplete + '%';
			bar.width(percentVal);
			$('.coverProgress').slideDown(200);
			percent.html(percentVal);
		},
		success: function (data) {
			$('.profile_cover').fadeIn(100);
			if(data.status == 200) {
				Wo_GetNewPosts();
				/* var image_id='cover-image-'+data.cover_id
				$('[id^='+image_id+']').attr("src", data.img);
				$('[id^='+image_id+']').attr("onclick", "Wo_OpenProfileCover('"+data.img+"')"); */
				
				$(".coverProgress").hide();
				var percentVal = '0%';
				bar.width(percentVal);
				percent.html(percentVal);
				
				$("#updateCoverMsg").html("<?php echo $wo['lang']['cover_image_upload'];?>").css("color", "green");
				
				setTimeout( function(){
					$('#updateCoverFrm').trigger("reset");
					$("#updateProfileCoverMdl").modal("hide");
					location.reload(true);
				}, 1500);
			
			} else {
				alert("Something went wrong, please try again.");
				//location.reload(true);
			}
			$('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
		}
	});
});

function Wo_GetFollowing(user_id) {
  Wo_progressIconLoader($('#sidebar-following-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_following_users',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-following-users-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-following-list-container').find('span'));
  });
}

function Wo_GetFollowers(user_id) {
  Wo_progressIconLoader($('#sidebar-followers-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_followers_users',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-followers-users-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-followers-list-container').find('span'));
  });
}

function Wo_GetLikes(user_id) {
  Wo_progressIconLoader($('#sidebar-pages-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'pages',
    s: 'get_likes',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-likes-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-pages-list-container').find('span'));
  });
}

function Wo_GetMoreFollowing(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.user-data:last').attr('data-user-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_more_following',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_users_to_show']; ?>");
      } else {
        $('#following-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_GetMoreUserLikes(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.user-data:last').attr('data-page-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'pages',
    s: 'get_more_likes',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_pages']; ?>");
      } else {
        $('#likes-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_GetMoreVideos(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.video-data:last').attr('data-video-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_more_videos',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_videos_to_show']; ?>");
      } else {
        $('#videos-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_GetMorePhotos(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.profile-lists .photo-data:last').attr('data-photo-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_more_photos',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_photos_to_show']; ?>");
      } else {
        $('#photos-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_GetMoreFollowers(user_id) {
  Wo_progressIconLoader($('.load-more').find('button'));
  after_last_id = $('.user-data:last').attr('data-user-id');
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_more_followers',
    user_id: user_id,
    after_last_id: after_last_id
  }, function (data) {
    if(data.status == 200) {
      if(data.html.length == 0) {
        $('.load-more').find('button').text("<?php echo $wo['lang']['no_more_users_to_show']; ?>");
      } else {
        $('#followers-list').append(data.html);
      }
    }
    Wo_progressIconLoader($('.load-more').find('button'));
  });
}

function Wo_UpdateProfileAvatar() {
  $("form.profile-avatar-changer").submit();
}

// function Wo_UpdateProfileCover() {
//   $("form.profile-cover-changer").submit();
// }

function Wo_UpdateProfileCover(cover_id) {
	//var formname='form.personal_image_'+cover_id;
	//console.log(formname);
	//$(formname).submit();
	$("#updateCoverId").val(cover_id);
	$("#updateProfileCoverMdl").modal("show");
}


function Wo_SetCookieAlert() {
  $.get(Wo_Ajax_Requests_File(), {
    f: 'set_admin_alert_cookie'
  });
}

function Wo_OpenProfileCoverDG(image, type) {
	
	var html = '';
	if(type == "video") {
		html += '<video class="video-js vjs-big-play-centered" preload="auto" autoplay controls style="width: 100%; height: 100%; cursor: pointer;" >';
			html += '<source src="'+image+'">';
			html += '<source src="'+image+'" type="video/webm">';
		html += '</video>';
	} else {
		html += '<img src="'+image+'" class="img-responsive">';
	}
	
	$("#ProfileCoverImageDGModal .modal-body").html(html);
	$("#ProfileCoverImageDGModal").modal("show");
}

function Wo_OpenProfileCover(image) {
    $.post(Wo_Ajax_Requests_File() + '?f=get_user_profile_cover_image_post', {
      image:image
    }, function (data) {
        if (data.status == 200) {
            Wo_OpenLightBox(data.post_id);
        } else {
            $('[id^=cover-image]').attr('data-target', '#ProfileCoverImageModal');
            $('[id^=cover-image]').attr('data-toggle', 'modal');
            $('#ProfileCoverImageModal').modal('show');
        }
    });
}

function Wo_OpenProfilePicture(image) {
    $.post(Wo_Ajax_Requests_File() + '?f=get_user_profile_image_post', {
      image:image
    }, function (data) {
        if (data.status == 200) {
            Wo_OpenLightBox(data.post_id);
        } else {
            $('[id^=updateImage-' + user_id + ']').attr('data-target', '#ProfileImageModal-' + user_id);
            $('[id^=updateImage-' + user_id + ']').attr('data-toggle', 'modal');
            $('#ProfileImageModal-' + user_id).modal('show');
        }
    });
}
function Wo_GetMutualFriends(user_id) {
  Wo_progressIconLoader($('#sidebar-mutual-list-container').find('span'));
  $.get(Wo_Ajax_Requests_File(), {
    f: 'get_mutual_users',
    user_id: user_id
  }, function (data) {
    if(data.status == 200) {
      $('.sidebar-mutual-users-container').html(data.html);
    }
    Wo_progressIconLoader($('#sidebar-mutual-list-container').find('span'));
  });
}

$(document).on('change','input[type=radio][name=post_type]',function(){
	$("#video_thumbnail").val('');
	if(this.value == 'video'){
		$(".videoThumbnail").show();
	} else {
		$(".videoThumbnail").hide();
	}
});

<?php if ( $wo['loggedin'] ){ ?>
    <?php if ( isset( $_GET['mode'] ) && $_GET['mode'] == 'opengift' ){ ?>
        $(document).ready(function() {
            setTimeout(() => {
                $('#gift_show_model').modal('show');
            }, 1000);
        });
    <?php } ?>
<?php } ?>
</script>