<div class="row" style="margin: 0px 15px 20px 15px;">
<div class="page-margin wow_content ml-4 col-sm-12">
	<div class="wo_page_hdng pag_neg_padd pag_alone">
		<div class="wo_page_hdng_innr">
			<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z"></path></svg></span> 
			<?php 
			// if ($wo['config']['connectivitySystem'] == 1) {
			// 	echo $wo['lang']['friends_btn'];
			// } else {
				echo $wo['lang']['followers'].' ('. trim(Wo_CountFollowers($wo['user_profile']['user_id'])).')';
			//}
			?> 
			<!-- <div style="font-weight:normal;margin-left: auto;">
				<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['user_profile']['username'] . '&type=family_list');?>" data-ajax="?link1=timeline&u=<?php echo $wo['user_profile']['username']?>&type=family_list"><?php echo $wo['lang']['family_members']; ?></a> 
			</div> -->
		</div>
	</div>
</div>
<div class="list-group profile-lists col-sm-12">
	<div id="followers-list" class="row" style="margin: 0;">
		<?php
		   if (Wo_FriendPrivacy($wo['user_profile']['id'],$wo['user_profile']['friend_privacy'])) {
				if (Wo_CountFollowers($wo['user_profile']['user_id']) == 0) {
					if ($wo['config']['connectivitySystem'] == 1) {
						echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" fill="currentColor"></path></svg>' . $wo['lang']['no_friends'] . '</div>';
					} else {
						echo '<div class="empty_state"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M16 17V19H2V17S2 13 9 13 16 17 16 17M12.5 7.5A3.5 3.5 0 1 0 9 11A3.5 3.5 0 0 0 12.5 7.5M15.94 13A5.32 5.32 0 0 1 18 17V19H22V17S22 13.37 15.94 13M15 4A3.39 3.39 0 0 0 13.07 4.59A5 5 0 0 1 13.07 10.41A3.39 3.39 0 0 0 15 11A3.5 3.5 0 0 0 15 4Z" fill="currentColor"></path></svg>' . $wo['lang']['no_followers'] . '</div>';
					}
				} else {
					foreach (Wo_GetFollowers($wo['user_profile']['user_id'],'profile',100) as $wo['UsersList']) {
					echo Wo_LoadPage('timeline/follow');
					} 
				}
			}
		?>
	</div>
	<div class="clear"></div>
</div></div>